server:
  port: 8788
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10
#应用的名字
spring:
  application:
    name: redis-server
  session:
    store-type: redis
    database: 5 # redis 5 存储session
    namespace: authSession
    flush-mode: immediate
  cache: #cache使用redis储存
    type: redis
    user: 
      name: 
      password: 
  redis: #Redis配置
    database: 1 # Redis数据库索引（默认为0）
    host: 172.20.10.3  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 5 # 连接池中的最小空闲连接
      timeout: 0 # 连接超时时间（毫秒）



