#####################################################################################################
######### server 配置
#####################################################################################################
server:
  port: 8956
#####################################################################################################
######### application 配置
#####################################################################################################
spring:
  application:
    name: microservice-user
#####################################################################################################
######### jdbc 配置
#####################################################################################################
  datasource:
    url: jdbc:mysql://localhost:3306/teacherIntegratEval?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#####################################################################################################
######### 日志 配置
#####################################################################################################
logging:
  level:
    root: INFO
    com.asiainfo.mapper: DEBUG
#####################################################################################################
######### eureka 配置
#####################################################################################################
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10
